CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Username VARCHAR(50) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
	[Password] VARCHAR(255) NOT NULL,
	BirthDate DATE NOT NULL,
	Gender VARCHAR(20) NOT NULL,
	ELO INT NOT NULL,
	[Role] VARCHAR(20) NOT NULL,
	CONSTRAINT CHK_ELO CHECK (ELO BETWEEN 0 AND 3000)
)
